# Generated by Django 5.0.1 on 2025-02-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_taskpermission_task_shared_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='shared_users',
        ),
    ]
