# Generated by Django 5.0.1 on 2025-02-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_task_shared_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpermission',
            name='permission_type',
            field=models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit'), ('delete', 'Delete')], default='view', max_length=10),
        ),
    ]
